#############################################################################
# Makefile for building: ARM_POS_Demo
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Feb 27 20:16:28 2014
# Project:  ARM_POS_Demo.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ARM_POS_Demo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabi -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = admindialog.cpp \
		main.cpp \
		mainwindow.cpp \
		IO.cpp \
		portutility.cpp \
		printer.cpp \
		ScannerAgentThread.cpp moc_admindialog.cpp \
		moc_mainwindow.cpp \
		moc_ScannerAgentThread.cpp \
		qrc_resourcefile.cpp
OBJECTS       = admindialog.o \
		main.o \
		mainwindow.o \
		IO.o \
		portutility.o \
		printer.o \
		ScannerAgentThread.o \
		moc_admindialog.o \
		moc_mainwindow.o \
		moc_ScannerAgentThread.o \
		qrc_resourcefile.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ARM_POS_Demo.pro
QMAKE_TARGET  = ARM_POS_Demo
DESTDIR       = 
TARGET        = ARM_POS_Demo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_admindialog.h ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ARM_POS_Demo.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabi/libQtGui.prl \
		/usr/lib/arm-linux-gnueabi/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ARM_POS_Demo.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabi/libQtGui.prl:
/usr/lib/arm-linux-gnueabi/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ARM_POS_Demo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ARM_POS_Demo1.0.0 || $(MKDIR) .tmp/ARM_POS_Demo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ARM_POS_Demo1.0.0/ && $(COPY_FILE) --parents admindialog.h mainwindow.h IO.h portutility.h printer.h ScannerAgentThread.h .tmp/ARM_POS_Demo1.0.0/ && $(COPY_FILE) --parents resourcefile.qrc .tmp/ARM_POS_Demo1.0.0/ && $(COPY_FILE) --parents admindialog.cpp main.cpp mainwindow.cpp IO.cpp portutility.cpp printer.cpp ScannerAgentThread.cpp .tmp/ARM_POS_Demo1.0.0/ && $(COPY_FILE) --parents admindialog.ui mainwindow.ui .tmp/ARM_POS_Demo1.0.0/ && (cd `dirname .tmp/ARM_POS_Demo1.0.0` && $(TAR) ARM_POS_Demo1.0.0.tar ARM_POS_Demo1.0.0 && $(COMPRESS) ARM_POS_Demo1.0.0.tar) && $(MOVE) `dirname .tmp/ARM_POS_Demo1.0.0`/ARM_POS_Demo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ARM_POS_Demo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_admindialog.cpp moc_mainwindow.cpp moc_ScannerAgentThread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_admindialog.cpp moc_mainwindow.cpp moc_ScannerAgentThread.cpp
moc_admindialog.cpp: admindialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) admindialog.h -o moc_admindialog.cpp

moc_mainwindow.cpp: admindialog.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_ScannerAgentThread.cpp: ScannerAgentThread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ScannerAgentThread.h -o moc_ScannerAgentThread.cpp

compiler_rcc_make_all: qrc_resourcefile.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resourcefile.cpp
qrc_resourcefile.cpp: resourcefile.qrc \
		picture/P_07.bmp \
		picture/P_08.bmp \
		picture/P_09.bmp \
		picture/P_10.bmp \
		picture/logo.jpg \
		picture/P_11.bmp \
		picture/P_01.bmp \
		picture/P_12.bmp \
		picture/P_02.bmp \
		picture/P_03.bmp \
		picture/P_04.bmp \
		picture/P_05.bmp \
		picture/P_06.bmp
	/usr/bin/rcc -name resourcefile resourcefile.qrc -o qrc_resourcefile.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_admindialog.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_admindialog.h ui_mainwindow.h
ui_admindialog.h: admindialog.ui
	/usr/bin/uic-qt4 admindialog.ui -o ui_admindialog.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

admindialog.o: admindialog.cpp admindialog.h \
		ui_admindialog.h \
		portutility.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o admindialog.o admindialog.cpp

main.o: main.cpp mainwindow.h \
		admindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		admindialog.h \
		ui_mainwindow.h \
		printer.h \
		portutility.h \
		ScannerAgentThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

IO.o: IO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IO.o IO.cpp

portutility.o: portutility.cpp portutility.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o portutility.o portutility.cpp

printer.o: printer.cpp printer.h \
		IO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printer.o printer.cpp

ScannerAgentThread.o: ScannerAgentThread.cpp ScannerAgentThread.h \
		portutility.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScannerAgentThread.o ScannerAgentThread.cpp

moc_admindialog.o: moc_admindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_admindialog.o moc_admindialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ScannerAgentThread.o: moc_ScannerAgentThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScannerAgentThread.o moc_ScannerAgentThread.cpp

qrc_resourcefile.o: qrc_resourcefile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resourcefile.o qrc_resourcefile.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

