@.  1b21 & 1d21 & 1b4d

!pABCDEFGHIJKLMNOPQRSTUVWXYZ
!€ABCDEFGHIJKLMNOPQRSTUVWXYZ
!0ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDFEGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
! ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
!@ABCDEFGHIJKLMNOPQRSTUVWXYZ
!PABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
MABCDEFGHIJKLMNOPQRSTUVWXYZ
MABCDEFGHIJKLMNOPQRSTUVWXYZ
!ABCDEFGHIJKLMNOPQRSTUVWXYZ
M ABCDEFGHIJKLMNOPQRSTUVWXYZ

VB 